# Generated by Django 3.0.6 on 2020-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=1500),
        ),
    ]
