# Generated by Django 3.0.6 on 2020-05-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200522_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
